hide-default-nametags: true

# PlaceholderAPI, MiniMessage support

nametag-format:
  line-height: 0.3
  text-opacity-on-sneak: 0.5 # Between 0.0 and 1.0
  lines:
    - "<green>{player_name}"
    - "<red>Hello world!"